### ISSUE TITLE
README中等宽字体下载链接问题

### ISSUE THREAD

**Issue by wzk0** [Chenyu-otf/chenyuluoyan_thin#8]
[这里的等宽字体下载链接](https://github.com/Chenyu-otf/chenyuluoyan_thin#%E9%BB%9E%E6%AD%A4%E4%B8%8B%E8%BC%89%E4%B8%8D%E7%AD%89%E5%AF%AC%E7%89%88%E6%9C%AC-%E9%BB%9E%E6%AD%A4%E4%B8%8B%E8%BC%89%E7%AD%89%E5%AF%AC%E7%89%88%E6%9C%AC)地址错误啦!

应该是: https://github.com/Chenyu-otf/chenyuluoyan_thin/releases/download/v1.0-monospaced/ChenYuluoyan-Thin-Monospaced.ttf

非常喜欢您的字体, 感谢!

**Comment by Chenyu-otf** [comment]
謝謝提醒，已經更正囉！
